<section class="container-l">

  <section class="welcome about">
    <img src="img/face.png" alt="" id="circle">
    <article class="about-item">
      <h2 class="title">About Me...</h2>

      <p>Hello, everyone!! I’m glad to meet you. My name is Hyeon jin Lee, but you can call me Jessica. I live in South Korea, where I teach English to lovely kids at the Kindergarten. I’m in my mid-thirties but I hope that I look younger than I am. <i class="far fa-smile-wink"></i></p>
      <p>As long as I remember, I've always loved to cook in my free time, especially for my family and friends. I learned a lot from helping my mother, she is such a great cooker. And I want now to share these wonderful recipes.</p>
      <p>Since I was 19 years, I've been enjoying travelling around the world: France, Italy, Australia, Norway, Sweden, Japan, Singapore, Indonesia... Many countries where I have met friends that I still keep in touch with. But I still have a lot of places to explore and new flavours to discover :)</p>
      <p>So, let’s learn how to cook Korean food and more!</p>
      <p>If you enjoy eating, you can be a great cooker too!
      Please continue to love cooking!</p>
    </article>

    <article class="about-pictures">
      <img src="img/smile.png" alt="" class="about-img">
      <img src="img/train.png" alt="" class="about-img">
      <img src="img/brother.png" alt="" class="about-img">
      <img src="img/bb.png" alt="" class="about-img">
      <p>Here is my nephew :)</p>
    </article>

  </section>

</section>
