<section class="welcome galleries container-m">
  <h2 class="title">Flowers</h2>

  <p>I'm a hands-on type of person, more of an artistic type, and I enjoy making flowers, decorative ones and ... edible ones !!! These flowers are made from bean paste, and they are usually used to decorate rice cakes. You wanna know more ? You will soon be able to watch tutorials on my YouTube channel.</p>

  <section class="gallery grid-container">
    <img src="img/flowers1.jpg" alt="" class="grid-item">
    <img src="img/flowers2.jpg" alt="" class="grid-item">
    <img src="img/flowers3.jpg" alt="" class="grid-item">
    <img src="img/flowers4.jpg" alt="" class="grid-item">
    <img src="img/flowers5.jpg" alt="" class="grid-item">
    <img src="img/flowers6.jpg" alt="" class="grid-item">
    <img src="img/flowers7.jpg" alt="" class="grid-item">
    <img src="img/flowers8.jpg" alt="" class="grid-item">
    <img src="img/flowers9.jpg" alt="" class="grid-item">
    <img src="img/flowers10.jpg" alt="" class="grid-item">
    <img src="img/flowers11.jpg" alt="" class="grid-item">
    <img src="img/flowers12.jpg" alt="" class="grid-item">
    <img src="img/flowers13.jpg" alt="" class="grid-item">
    <img src="img/flowers14.jpg" alt="" class="grid-item">
    <img src="img/flowers15.jpg" alt="" class="grid-item">
    <img src="img/flowers16.jpg" alt="" class="grid-item">
    <img src="img/flowers17.jpg" alt="" class="grid-item">
    <img src="img/flowers18.jpg" alt="" class="grid-item">
    <img src="img/flowers19.jpg" alt="" class="grid-item">
    <img src="img/flowers20.jpg" alt="" class="grid-item">
    <img src="img/flowers21.jpg" alt="" class="grid-item">
  </section>

</section>
