<section class="welcome home container-m">
  <h2 class="title">Welcome!</h2>

  <p>I am a Korean girl, teaching English to lovely kids and a true food addict.</p>
  <p>I feel happy about all things related to food. When I’m happy or sad... I cook! That’s a passion!</p>
  <p>You'll discover here a few family recipes, as well as delicious pastries recipes and others yummies.</p>
  <p> Enjoy! And bon appétit!</p>
</section>

<hr class="container-s hr-main">

<section class="video-section container-l">
  <h3>Great videos as appetizers...</h3>
  <div class="video">
    <div class="videoWrapper">
        <iframe width="480" height="360" src="https://www.youtube.com/embed/38ZyFsjKWpQ" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    </div>
    <article class="video-article">
      <p>You'll soon enjoy my YouTube channel about food and others discoveries! I'm working on it... Right now, enjoy one of my favorites recipes made by another great cooker...</p>
    </article>
  </div>

  <div class="video">
    <iframe width="480" height="360" src="https://youtube.com/embed/L6JHeVsakG4" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    <article class="video-article">
      <p>You wanna learn some more? Let's enjoy this delicious video introducing cultural and historical aspects of the Korean kitchen...</p>
  </div>
</section>

<section class="video-section container-l">
  <h3>For those learning Korean...</h3>
  <div class="video">
    <iframe width="480" height="360" src="https://www.youtube.com/embed/0AtWR-mdLNA" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    <article class="video-article">
      <p>Let's discover this amazing Bibimguksu: Korean Spicy Cold noodles. This video is in Korean, but I promise you'll soon be able to watch it in English.</p>
    </article>
  </div>
  <section class="video">
    <a href="https://blog.naver.com/lasprass" target="_blank"><img src="img/blog.jpg" alt="blog"></a>
    <div class="blog-item">
      <p>And if you know already a bit of Korean, you can start discovering tones of recipes on <a href="https://blog.naver.com/lasprass" target="_blank" class="a-style">my blog</a>. I suggest you take a look at it with the translation option... </p>
    </div>
  </section>
</section>

<section class="k-event container-l">
  <h3>K-Culture in Paris!</h3>
  <p class="k-event-intro">If you wanna enjoy Korean exhibitions or events in Paris.</p> 
  <section class="k-event-section"></section>
</section>

<section class="besties container">
    <div class="bck-img"><img src="img/girl.jpg" alt="food"></div>
    <div class="bck-img"><img src="img/family.jpg" alt="food"></div>
    <div class="bck-img"><img src="img/girlmoon.jpg" alt="food"></div>
    <div class="bck-img"><img src="img/hanbok.jpg" alt="food"></div>
</section>

<script src="js/main.js"></script>
<script src="js/koreaParis.js"></script>
