
<section class="form-section">

  <h2 class="title">Contact me!</h2>

  <form action="mail.php" method="post" class="sign container-s">
    <input type="text" name="Name" placeholder="Your name" class="sign-item" required/>

    <input type="email" name="Email" placeholder="Your email" value="" class="sign-item" required/>

    <textarea id="message" name="Message" rows="10" cols="30" placeholder="Your message here..." class="sign-item"></textarea>

    <input type="submit" name="Valider" value="Send" class="sign-item-submit sign-item"/>
  </form>


</section>
