<section class="welcome galleries container-m">
      <h2 class="title">Yummi Pastries</h2>

      <p>I enjoy travelling all around the world,<br> and thanks to my Western trips I discovered many flavoured pastries... </p>
      <p>Let's bake a few of them ! As well as Korean pastries you should taste !<br> You can find all these recipes on <a href="https://blog.naver.com/lasprass" target="_blank" class="a-style">my Korean blog</a>, and videos will be posted online very soon, on my YouTube channel.</p>

      <section class="gallery grid-container">
        <img src="img/pastries1.jpg" alt="" class="grid-item">
        <img src="img/pastries2.jpg" alt="" class="grid-item">
        <img src="img/pastries3.jpg" alt="" class="grid-item">
        <img src="img/pastries4.jpg" alt="" class="grid-item">
        <img src="img/pastries5.jpg" alt="" class="grid-item">
        <img src="img/pastries6.jpg" alt="" class="grid-item">
        <img src="img/pastries7.jpg" alt="" class="grid-item">
        <img src="img/pastries8.jpg" alt="" class="grid-item">
        <img src="img/pastries9.jpg" alt="" class="grid-item">
        <img src="img/pastries10.jpg" alt="" class="grid-item">
        <img src="img/pastries11.jpg" alt="" class="grid-item">
        <img src="img/pastries12.jpg" alt="" class="grid-item">
        <img src="img/pastries13.jpg" alt="" class="grid-item">
        <img src="img/pastries14.jpg" alt="" class="grid-item">
        <img src="img/pastries15.jpg" alt="" class="grid-item">
        <img src="img/pastries16.jpg" alt="" class="grid-item">
        <img src="img/pastries17.jpg" alt="" class="grid-item">
        <img src="img/pastries18.jpg" alt="" class="grid-item">
        <img src="img/pastries19.jpg" alt="" class="grid-item">
        <img src="img/pastries20.jpg" alt="" class="grid-item">
        <img src="img/pastries21.jpg" alt="" class="grid-item">
      </section>


      </section>
