<section class="form-section">

	<h2 class="title signup">Sign up !</h2>


	<form id="register-form" class="sign container-s" action="register.php" method="POST">

		<input type="text" name="LastName" placeholder="Your first name" class="sign-item" required/>

		<input type="text" name="FirstName" placeholder="Your last name" class="sign-item" required/>

		<input type="email" name="Email" placeholder="Your email" value="" class="sign-item" required/>

		<input type="password" name="Password" placeholder="Your password" value="" class="sign-item" required/>

		<input type="submit" name="Valider" value="Sign Up" class="sign-item-submit sign-item"/>

	</form>

</section>
